# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
